### ISSUE TITLE
ブランチ名のprefixの統一

### ISSUE THREAD

**Issue by rhiroe** [yasasii-team/regulus#11]
各ブランチの目的がわかりやすくなるようにprefixを統一する
個人的に以下がしっくり来ているので特に意見等なければ以下を採用する
https://twitter.com/ITF_sudame/status/1102194158746382341 より
![prefix](https://pbs.twimg.com/media/D0vHvRuV4AEXrPd.jpg)

**Comment by rhiroe** [comment]
ツイート元にもあるように`clean`は`refactor`に変更した方がわかりやすいかもしれない

@deltama37 
@takahashi19 
何か意見などあればお願いします。
なければこのまま採用しますので意思表示をお願いします。
採用したものをWikiにまとめておきます。

**Comment by deltama37** [comment]
普段自分はhttps://qiita.com/Jung0/items/0a9a7a97a2c17f92d3c5 のスタイルでやってますが特にこだわりないので合わせます

**Comment by rhiroe** [comment]
@deltama37 
文字より見分けがつきやすいのでいいですね！
ただ文字じゃない分、認識を共有していないと見た目じゃわからないので
きちんと共有していきましょう。

絵文字にするかどうかは最後に決めるとして、種類的には上記で問題なさそうですか？

今気づいたんですけど、これブランチ名じゃなくてコミットメッセージですねw
コミットメッセージは各自好きなように付ければ良いかなと思っています。

**Comment by rhiroe** [comment]
@ToshinoriIzumi 
何か意見などあればよろしくお願いします。
特になければその意思表示だけお願いします。

**Comment by deltama37** [comment]
ああ、コミットメッセージのprefixの話かと思ってましたww
特に指定ないので合わせます

**Comment by rhiroe** [comment]
とりあえずこれを採用します。
`clean`のみ`refactor`に変更します。
