### ISSUE TITLE
Rails new する

### ISSUE THREAD

**Issue by rhiroe** [yasasii-team/regulus#13]
個人的な要望を書いておくけどDocker事情に合わせてよしなにしてくれると助かる。
勝手に`rails new`してもいいならやるので教えてください。

minitestは使わないので自動生成しない(`-T`)
DBはpostgreSQLを使う(`-d postgresql`)
ruby及びrailsは最新安定バージョンを使う
Ruby 2.6.2
Rails 5.2.3
```bash
$ rails _5.2.3_ new . -T -d postgresql
```
```ruby
group :development, :test do
  # rspecを使う
  gem 'rspec-rails'
end

group :development do
  # 汚いコードに指摘が入る、絶対に入れて欲しい
  # コーディングルールについてまでレビューするのはしんどいよね？
  gem 'rubocop'
  # モデルにschemaがコメントされる
  # routesに $ rails routes がコメントされる
  # あれば便利、なくてもいい
  gem 'annotate'
end
```
```bash
$ rails generate rspec:install
```
一緒に`gem 'spring-commands-rspec'`も入れると
`$ bin/rspec`が使えるようになって高速化が期待できるが
今回のアプリはそんなに大きくないので入れなくても良い。
```ruby
Rails.application.config do |config|
  config.generators do |g|
    g.test_framework :rspec,
      fixtures: false,
      view_specs: false,
      helper_specs: false,
      routing_specs: false,
      # ControllerSpecは生成されないようにして
      controller_specs: false,
      # RequestSpecが生成されるようにする
      request_specs: true
  end
  # 何かあると面倒なのでついでに諸々日本時間になるようにする
  config.time_zone = "Tokyo"
  config.active_record.default_timezone = :local
end
```
rubocopの設定
```.rubocop.yml
# Rails用の設定を有効化
Rails:
  Enabled: true
# 日本語でのコメントが指摘されないように
Style/AsciiComments:
  Enabled: false
```
あとは必要になったタイミングで考えれば良いかなと。

**Comment by deltama37** [comment]
@eRy-sk お！じゃーお願いしてもいいですか

**Comment by deltama37** [comment]
spring-commands-rspecはどちらでもいいです

**Comment by rhiroe** [comment]
昨日の話の感じだとフロントを作るようになるかもしれないとのことだったので
APIモードではなく普通にRails newする感じでOKですか？

**Comment by deltama37** [comment]
OKです！

**Comment by rhiroe** [comment]
rubocopは
```bash
$ rubocop
```
で全ファイル、ファイル名を指定すればそのファイルでの指摘を確認できますが
この使い方は確認もめんどくさいので、
エディターに直接指摘が来るようにプラグインなど導入してください。
例えばAtomだとhttps://github.com/AtomLinter/linter-rubocop とか
https://qiita.com/MasakatsuNakamura/items/eb91ed2945bb145d4a5f
