### ISSUE TITLE
作るアプリを決める

### ISSUE THREAD

**Issue by deltama37** [yasasii-team/regulus#3]
新刊漫画をLINEBot使って垂れ流す

新刊のデータは
https://books.rakuten.co.jp/event/book/comic/calendar/js/booklist.json
でjsonで取得

https://books.rakuten.co.jp/event/book/comic/calendar/2019/03/js/booklist.json
こんな感じで過去のデータも取得可能

細かい機能、仕様は未定

https://scrapbox.io/rails-team/2019.04.02%E4%BC%9A%E8%AD%B0

**Comment by rhiroe** [comment]
@deltama37 @ToshinoriIzumi @takahashi19
これ決めないと進まないみたいなので早く話し合って決めましょう。
会議して決めるのでもいいですしチャットで決めるのでもいいです。

#5 を approved しておいてなんですが、APIを作るだとかVue.jsを使わないだとかになると
revertした方が楽ですね。ちょっとマージ早まった。

**Comment by deltama37** [comment]
会議に一票で

まああれだったらrevertしましょう

**Comment by rhiroe** [comment]
一応方向性は決まったのでクローズします。
まだ気になること、異議などあれば再開してください。
